### ISSUE TITLE
[+] Failed to search query. LDAP Result Code 4 "Size Limit Exceeded": 

### ISSUE THREAD

**Issue by 0xVIC** [AidenPearce369/ADReaper#1]
Hello, 
Very nice tool thanks, I got thar error, **[+] Failed to search query. LDAP Result Code 4 "Size Limit Exceeded":** 

A higher limit could be implemented for the query of AD users.
Cheers.

**Comment by m0n1x90** [comment]
> Hello, 
> Very nice tool thanks, I got thar error, **[+] Failed to search query. LDAP Result Code 4 "Size Limit Exceeded":** 
> 
> A higher limit could be implemented for the query of AD users.
> Cheers.

Hey there,

Could you please attach the screenshot and for which query are you trying, Group LDAP query IG

**Comment by RedTeams** [comment]
I also faced the same issue for the following queries (I have masked some fields because of the environment I was testing).
```
 ./ADReaper -command users -dc dc.example.local -password Password1 -user pentest@example.local
./ADReaper -command user-logs -dc dc.example.local -password Password1 -user pentest@example.local
./ADReaper -command groups -dc dc.example.local -password Password1 -user pentest@example.local
./ADReaper -command  never-loggedon -dc dc.example.local -password Password1 -user pentest@example.local
```

However, all the other queries worked well...

**Comment by crypt0rr** [comment]
Same issue over here. @AidenPearce369 as you requested, here a screenshot. For example, the `dc` and `computers` option works fine.

![adreaper](https://user-images.githubusercontent.com/57799908/165079975-0164e0ad-3696-49a6-bbb8-d937bdb0cf61.png)

**Comment by m0n1x90** [comment]
@0xVIC @RedTeams @crypt0rr  could you check now. I have resolved the pagination for LDAP output. It should display the users/computers/groups correctly even if it is a large list

**Comment by crypt0rr** [comment]
> @0xVIC @RedTeams @crypt0rr could you check now. I have resolved the pagination for LDAP output. It should display the users/computers/groups correctly even if it is a large list

Works fine now, also see screenshot.
![adreaper](https://user-images.githubusercontent.com/57799908/165692887-8f1f3dbb-e468-44b0-8108-5cce581ac685.png)

**Comment by m0n1x90** [comment]
Check out the new features too... If you face any issues let me know
